# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: JohninchのBlog
subtitle: Inch
description: 张宇驰的博客主页
keywords: [FED, Juve]
author: Johninch
language: zh-Hans
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://johninch.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: melody

Plugins:
  - hexo-algoliasearch

algolia: 
  appId: "0XJEPPY0XU"
  apiKey: "e06877afb5799837e43083eaa72dae92"
  adminApiKey: "c31a8f09d9411ecda8bd20aef96bb600"
  chunkSize: 5000
  indexName: "inch-blog"
  fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - title
    - tags
    - categories
    - slug
    - gallery
    - slides
    - permalink
    - path
    - contentStripTruncate

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/johninch/johninch.github.io #https://bitbucket.org/JohnSmith/johnsmith.bitbucket.io
  branch: master #published
  message: deploy

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-tororo
  display:
    position: right
    width: 200
    height: 400
  mobile:
    show: true
  react:
    opacity: 0.7
    opacityDefault: 0.7
    opacityOnHover: 0.2
